[project]
authors = ["Igors Dubanevics <26872977+igorsdub@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "python-testing"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks.test]
cmd  = "pytest {% if coverage %} --cov {% endif %} -v"
args = [{ arg = "coverage", default = "" }]

[tasks.lint]
cmd  = "ruff check {% if fix %} --fix {% endif %} src/"
args = [{ arg = "fix", default = "" }]

[tasks.ci]
depends-on = [
  { task = "lint", args = ["fix"] },
  { task = "test", args = ["coverage"] }
]

[dependencies]
pytest = ">=8.4.1,<9"
numpy = ">=2.3.1,<3"
pytest-cov = ">=6.2.1,<7"
ruff = ">=0.12.2,<0.13"
